---
- name: Netbox Events
  hosts: all
  execution_strategy: parallel
  vars:
    # webhook_port: 5001
  sources:
    - ansible.eda.webhook:
        port: "{{ webhook_port | default(5000) }}"
        token: "{{ webhook_token | default(omit) }}"
  rules:
    - name: Netbox | Interface Update Access
      condition: |
        event.payload.event == "updated" and
        event.payload.model == "interface" and
        event.payload.data.mode.value == "access"
      action:
        run_workflow_template:
          name: Netbox - Interface Update
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload.data.device.name }}"
              switchport_mode: "{{ event.payload.data.mode.value }}"
              interface_name: "{{ event.payload.data.name }}"
              interface_description: "{{ event.payload.data.description }}"
              # tagged_vlans: "{{ event.payload.data.tagged_vlans | map(attribute='id') | list }}"
              # tagged_vlans: "{{ event.payload.data.tagged_vlans | default(omit) }}"
              untagged_vlan: # "{{ event.payload.data.untagged_vlan }}"
                name: "{{ event.payload.data.untagged_vlan.name }}"
                vid: "{{ event.payload.data.untagged_vlan.vid }}"

    - name: Netbox | Interface Update Trunk
      condition: |
        event.payload.event == "updated" and
        event.payload.model == "interface" and
        event.payload.data.mode.value == "trunk"
      action:
        run_workflow_template:
          name: Netbox - Interface Update
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload.data.device.name }}"
              switchport_mode: "{{ event.payload.data.mode.value }}"
              interface_name: "{{ event.payload.data.name }}"
              interface_description: "{{ event.payload.data.description }}"
              # tagged_vlans: "{{ event.payload.data.tagged_vlans | map(attribute='id') | list }}"
              tagged_vlans: "{{ event.payload.data.tagged_vlans }}"
              # untagged_vlan: "{{ event.payload.data.untagged_vlan | default(omit) }}"
                # name: "{{ event.payload.data.untagged_vlan.name }}"
                # vid: "{{ event.payload.data.untagged_vlan.vid }}"

    - name: Netbox | Unhandled Events
      condition: event.payload is defined
      action:
        debug: